version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql
    container_name: hot-item-collector
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul

#  db_dummy:
#    image: mysql
#    container_name: dummy-hot-item-collector
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DUMMY_DATABASE}
#      MYSQL_ROOT_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "3308:3306"

  redis:
    image: redis
    container_name: hot-item-collector-redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo
    container_name: hot-item-collector-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  rabbitmq:
    image: rabbitmq
    container_name: hot-item-collector-rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
      - "61613:61613"  # STOMP port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
