### 로그인 - 유저1
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "loginId": "user1",
  "password": "passWord123!"
}

> {%
    client.global.set("access_token", response.body.result.access);
    client.global.set("refresh_token", response.body.result.refresh);
%}

### 로그인 유저 2
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "loginId": "user2",
  "password": "passWord123!"
}

> {%
    client.global.set("access_token", response.body.result.access);
    client.global.set("refresh_token", response.body.result.refresh);
%}

### 채팅방 생성
POST http://localhost:8080/chatroom
Content-Type: application/json
Authorization: {{access_token}}

{
  "seller": "someone Lee"
}

### 채팅방 조회
GET http://localhost:8080/chatroom/5f176cc5-e620-4b22-b58b-8a5ab8af979a

### 채팅 생성
POST http://localhost:8080/chat/message
Content-Type: application/json
Authorization: {{access_token}}

{
    "roomId": "someone Lee_someone Kim",
    "message": "나는 안녕 한데?"
}

### Create or Get Chat Room
POST http://localhost:8080/chatroom
Content-Type: application/json
Authorization: {{access_token}}

{
  "seller": "someone Lee"
}

> {% client.global.set("roomId", response.body.roomId); %}

### Send Chat Message
POST http://localhost:8080/pub/chat/message
Content-Type: application/json
Authorization: {{access_token}}

{
  "roomId": "{{roomId}}",
  "message": "Hello, this is a test message"
}