### 로그인 - 유저1
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "loginId": "user1",
  "password": "passWord123!"
}

> {%
    client.global.set("access_token", response.body.result.access);
    client.global.set("refresh_token", response.body.result.refresh);
%}

### 채팅 보내기
POST http://localhost:8080/chat/message
Content-Type: application/json
Authorization: {{access_token}}

{
  "id": "1",
  "roomId" : "1",
  "message" : "뭔데",
  "sender" : "123"
}